# Generated by Django 6.0.6 on 2026-06-22 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Éxito'), ('FAILED', 'Fallido')], max_length=10)),
                ('unpaid_count', models.PositiveSmallIntegerField(default=0)),
                ('action_taken', models.CharField(choices=[('NONE', 'Sin acción'), ('SUSPEND', 'Suspendida'), ('UNSUSPEND', 'Reactivada')], default='NONE', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_cobranza', to='linea.lineaservicio')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_rubro', models.CharField(choices=[('NO_PAGADO', 'No pagado'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='NO_PAGADO', max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubros', to='linea.lineaservicio')),
            ],
            options={
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
