# Generated by Django 6.0.6 on 2026-07-13 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('linea', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=3)),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('interes', models.CharField(blank=True, max_length=255)),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=5)),
                ('prioridad_score', models.PositiveSmallIntegerField(default=0)),
                ('etapa_embudo', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CALIFICADO', 'Calificado'), ('EN_NEGOCIACION', 'En negociación'), ('GANADO', 'Ganado'), ('PERDIDO', 'Perdido')], default='NUEVO', max_length=20)),
                ('origen', models.CharField(default='chat_web', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='cliente.cliente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(default='web_chat', max_length=20)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True)),
                ('objeciones', models.TextField(blank=True)),
                ('siguiente_accion_sugerida', models.CharField(choices=[('AGENDAR', 'Agendar reunión'), ('ENVIAR_MATERIAL', 'Enviar material educativo'), ('DERIVAR_ESPECIALISTA', 'Derivar a especialista'), ('NONE', 'Sin acción')], default='NONE', max_length=25)),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('EDITADA', 'Editada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='crm_agent.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('LEAD', 'Lead'), ('AGENTE_IA', 'Agente IA'), ('EJECUTIVO', 'Ejecutivo')], max_length=10)),
                ('contenido', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='crm_agent.conversacion')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], default='ABIERTA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm_agent.lead')),
                ('linea_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linea.lineaservicio')),
            ],
        ),
        migrations.CreateModel(
            name='TutorSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_interes', models.CharField(max_length=150)),
                ('fuente_contenido', models.CharField(blank=True, max_length=255)),
                ('quiz_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consentimiento_registrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_agent.lead')),
            ],
        ),
    ]
